### PR TITLE
#159204713 Set up continuous integration

### PR DESCRIPTION
**Pull request by Oluwafayokemi**
## What does this Pr do?
Integrate TravisCI with readme badge

## Description of tasks to be completed
- Set up Travis
- install mocha
- install chai
- set up coveralls
- add badge to read me
## How should this be manually tested
run npm test on your terminal
## What are the necessary pivotal tracker stories?
https://www.pivotaltracker.com/n/projects/2185767

### CODE REVIEW

**Comment by Veraclins** [comment]
Hi, Your PR is requesting a merge to `master`. You may want to look into it and make the PR to develop.

**Review by Veraclins — COMMENTED** [review]
I just realised the task also require adding CI badges to the readme. You may also consider adding that to the PR

**Comment by yomigeek** [comment]
Following the convention stated in the wiki, the branch should be named: chore/159204713/set-up-travis instead of chore/159204713/set-up/travis

**Comment by yomigeek** [comment]
I went through the folder structure, I can't find the server folder, and rest as we agreed upon in the team that you should take care of this while you complete this task.

**Comment by Oluwafayokemi** [comment]
Thank you for the feedback. I have made changes to the branch name. Please
check the branch folder, the server folder is ther

**Comment by Oluwafayokemi** [comment]
Thank you, Clinton. I have implemented the feedback

**Pull request closed without merging**
