### PR TITLE
#159204720 Completes user create and update profile endpoints

### PR DESCRIPTION
**Pull request by chukwuemekachm**
#### What does this PR do?
- Completes user create and update profile endpoints
#### Description of Task to be completed?
- Write unit tests for user get profile endpoint
- Create GET route to `/api/user`
- Add getUserProfile method in ProfileController.js to return the profile of the authenticated user
- Write unit tests for user update profile endpoint
- Create PUT route to `/api/user`
- Add updateUser method in userValidation.js to validate the request payload
- Add userEmailExists method in ProfileController.js to prevent email duplication
- Add updateUserProfile method in ProfileController.js to update the user profile
- Modify the datatype of bio to TEXT on user-migration file
- Test endpoint using POSTMAN
#### How should this be manually tested?
- Clone the repository
- Start up the command line /Terminal
- Change to the repo directory
- Run `npm install`
- Run `npm run migrate`
- Run `npm run dev`
- Use POSTMAN to create a PUT request to `/api/user`
- Use POSTMAN to create a GET request to `/api/user`
#### Any background context you want to provide?
- Create a Postrgresql database before you start
- Add a `.env` file to the project root
- Use the `.env.example` file in the project root to provide the necessary env-variables in your `.env`
- Request payload for the PUT request

``` 
{
"firstName": "John",
"lastName": "Doe",
"email": "johndoe@gmail.com",
"bio": "John Doe was born in 1977 when he arrived in Los Angeles. His previous life in Tennessee, Wisconsin & Baltimore was a great & fertile time but new music and social changes led him to events that created a life in art. He graduated from Antioch College in Baltimore in 1975, worked as a roofer, aluminum siding mechanic, and ran a poetry reading series. Ms. Meyers was his landlord in the rural black community of Simpsonville , MD.",
"image": "https://google.com/image/John-Doe"
}
```

#### What are the relevant pivotal tracker stories?
[#159204720](https://www.pivotaltracker.com/story/show/159204720)
#### Screenshots (if appropriate)

screen shot 2018-08-02 at 1 38 33 pm

screen shot 2018-08-02 at 1 43 24 pm

#### Questions:
- None

### CODE REVIEW

**Review by yomigeek — APPROVED** [review]
Good job. Welldone. I like the consistency around the conventions used.

**Review by Veraclins — APPROVED** [review]
This is really nice @chukwuemekachm, I can't find any issues here. This shows that you are taking your time and paying attention to details. Keep it up as this will go a long way in moulding you into the professional that you want to be.
I will simply advise that you look at HoundCi's comment and fix them. good job!

**Review by madeofhuman — APPROVED** [review]
You did a really good job, @chukwuemekachm. When the only noticeable issues are two HoundCI technicalities, then you did an excellent work. Find time to fix them and we're good. 💯 💯

**Review by tonymontaro — APPROVED** [review]
Excellent work.

**Pull request merged**
