### PR TITLE
#159848700 Integrate plagiarism checker for new articles

### PR DESCRIPTION
**Pull request by madeofhuman**
#### What does this PR do?
- run a plagiarism check on new articles that are not attributed

#### Description of Task to be completed?
- consume CopyLeaks API
- create a middleware that uploads text in article body to CopyLeaks for scanning if `req.attributes = false`, or does nothing if `true`
- prevent article creation if CopyLeaks API returns a result > 50% match until `req.isAttributed === true`
- to maximise CopyLeaks credits (free plan gives 25 credits at 1 credit per scan), don't run the scan if `process.env.NODE_ENV !== test`
- since the free version of Copyleaks gives us a limited number of credits for scanning (25), at one credit per scan, notify AH admin when the credits have run out

#### How should this be manually tested?
 - clone the repo: Run `git clone https://github.com/andela/elven-ah.git` in the folder where you want the repo to be saved.
 - navigate into the newly created folder and install the dependencies: `cd elven-ah && npm install`
 - copy .env.example to .env: `cp .env.example .env`
 - provision a PostgreSQL database and add the credentials to the .env file.
 - start the server using `npm start`
 - create an article by making a `POST` request to `/api/articles` with `isAttributed` property set to either `true` or `false`

#### Any background context you want to provide?
An ideal usage of the CopyLeaks API would be as a paid customer, but since it's quite expensive given the task at hand, I opted for just creating a new account and swapping the API key when it expires. This is not optimal for production where we'll have a lot of users creating lots of articles.

#### What are the relevant pivotal tracker stories?
[#159848700](https://www.pivotaltracker.com/story/show/159848700)

#### Screenshots (if appropriate)
screen shot 2018-08-23 at 10 33 26 am
screen shot 2018-08-23 at 10 35 15 am

#### Questions:
N/A

[Finishes #159848700]

### CODE REVIEW

**Review by chukwuemekachm — CHANGES_REQUESTED** [review]
Welldone @madeofhuman, I like your use of promises, async and await, it's very sweet. I understand that due to credits on the COPYLEAKS API we can't unit test the scanning mechanism. However don't you feel it's essential that we unit test other functions like `login` and `accesstoken`. I feel this would help to increase the coverage drop on this branch which is now at `-3.3%`.

**Comment by madeofhuman** [comment]
Yeah, you're right, @chukwuemekachm. I discussed that with @Veraclins, and I'm doing it now. Thanks for the review.

**Review by Veraclins — COMMENTED** [review]
@madeofhuman, this is quite nice. Good job! My only concern is the lack of tests which you are already trying to remedy. Great work!

**Review by chukwuemekachm — APPROVED** [review]
Welldone @madeofhuman .

**Review by Veraclins — APPROVED** [review]

**Review by Oluwafayokemi — APPROVED** [review]
Good job @madeofhuman

**Pull request merged**
