### PR TITLE
#159204714 Configure Authors Haven to use PostgreSQL as DB Engine

### PR DESCRIPTION
**Pull request by Veraclins**
#### What does this PR do?
Configure the API to use PostgreSQL as the database engine using Sequelize
#### Description of Task to be completed?
- Remove MongoDB configurations
- Setup PostgreSQL/Sequelize database config
- Configure Sequelize model to connect to the DB
- Add controller classes/methods to test/connect to the DB
- add test route for the DB connection test
#### How should this be manually tested?
- Clone the repo: Run `git clone https://github.com/andela/elven-ah.git` in the folder where you want the repo to be saved.
- Navigate into the newly created folder and install the dependencies: `cd elven-ah && npm install`
- Copy .env.example to .env: `cp .env.example .env`
- Provision a PostgreSQL database and add the credentials to the .env file. 
- Start the server using `npm start`
- Make a POST request to http://localhost:3000/users/testUser using postman submitting the following fields in the body of x-www-form-urlencoded or as raw JSON:
    - username
    - email
    - password
#### What are the relevant pivotal tracker stories? 
[#159204714](https://www.pivotaltracker.com/story/show/159204714)
#### Screenshots
screen shot 2018-07-26 at 7 18 34 pm

### CODE REVIEW

**Review by Oluwafayokemi — CHANGES_REQUESTED** [review]
Good job Clinton!
Weldone on successfully completing this chore, however, your commit message does not follow this https://github.com/andela/elven-ah/wiki/Commit-Message-Convention and your PR message does not follow the wiki convention at https://github.com/andela/elven-ah/wiki/Pull-Request-Naming-and-Description-Convention. This is important because the Github is linked to the pivotal tracker, therefore not following the right convention might not allow your work progress reflect on the PT board. Please follow the wiki convention for your commit message, PR message and all that you do. Secondly, I noticed you have 3 commits on the branch, I am not sure that is what the Atomic commit says. This chore is one task, i think you should have just one detailed commit for this task. I got this from the atomic commit 'Only commit when a block of work is complete
'.

**Comment by Veraclins** [comment]
Hi @Oluwafayokemi, thanks for taking the time to review the work and give me feedback. In order to be clear what is really expected of me, I need you please clarify some of the points you raised.


> **Commit message does not follow convention:**

screen shot 2018-07-27 at 7 39 11 am
Are you refering to the fact that it does not have the keyword 'finishes'? If that is the case, it is because that commit does not actually finish the task. That is why only the last commit has that keyword as adding the keyword normally marks the task finished on the PT board.


> **PR message does not follow convention:**

screen shot 2018-07-27 at 7 34 16 am
Please, can you be a bit more specific about how it did not follow the convention? I can't seem to find what I am doing wrong.


> **Having three commits on the branch:**

I did that in an attempt to implement the feedback I received yesterday from @tonymontaro about not having a single commit so that my task could be reviewed more easily by following the commits. I may have misunderstood him but I thought he meant I was not supposed to lump everything into a single commit.

Please let me know your thoughts so I can make any changes that may be necessary. Thanks.

**Review by madeofhuman — COMMENTED** [review]
@Veraclins, I think what Fayo was talking about is that your commit message does not include the scope of the change. For example:

```
chore(db): change app db from mongodb to postgres

- stuff
- stuff
- extra stuff

[delivers #12345678]
```
The scope in this commit is _db_ (in the bracket after the type of commit), which shows the area the change was made. Your commit messages lack that.

About the commit message footer, you can use `[Delivers #12345678]` if you're not yet done with the task. This will not finish the story on PT.

**Review by chukwuemekachm — COMMENTED** [review]
A good job @Veraclins . Personally, I prefer a single commit with its body being as explicit as possible, this is because it is easier to go through the files and see if the changes conform to the commit's description. But there is no best way of doing things. I believe you are trying to follow atomic commits. So I believe only @tonymontaro can solve this.

**Comment by Veraclins** [comment]
@madeofhuman @Oluwafayokemi @chukwuemekachm. I have squashed the commits into one. Please review and let me know if it is now ok?

**Review by chukwuemekachm — APPROVED** [review]
Nice one @Veraclins .

**Comment by yomigeek** [comment]
Nice job @Veraclins ...

**Review by Oluwafayokemi — APPROVED** [review]

**Review by tonymontaro — APPROVED** [review]
Excellent work guys, I love the team spirit. The commit message is perfect the way it is (with the three subtasks summarized in the body). If you prefer to commit those subtasks separately, that's great too. Just ensure that the pivotal tracker ID is in the commit message as described in the wiki.

**Pull request merged**
