### PR TITLE
#159268722 Refactor Codebase to ES6 Syntax

### PR DESCRIPTION
**Pull request by Veraclins**
#### What does this PR do?
Convert the codebase from ES5 syntax to ES6 syntax
#### Description of Task to be completed?
- convert ES5 codes to ES6
- add Babel and babel-plugins for transpiling ES6
- add .env.example
- add Eslint config for consistency of code
- add app installation process to the readme
#### How should this be manually tested?
- Clone the repo: Run `git clone https://github.com/andela/elven-ah.git` in the folder where you want the repo to be saved.
- Navigate into the newly created folder and install the dependencies: `cd elven-ah && npm install`
- Start the server using `npm start` 
- Visit http://localhost:3000 on a browser or postman.
#### What are the relevant pivotal tracker stories?
#159268722

### CODE REVIEW

**Review by madeofhuman — CHANGES_REQUESTED** [review]
You did a great work, Clinton. A few things to note, though: you pushed your _.env_ file which creates a huge security risk. Add it to your _.gitignore_ and untrack.

Also, I see you added _package-lock.json_ to your _.gitignore_ . but it still got uploaded because you did not untrack it. You can do that by running `git rm --cached :path_to_untrack`

Another thing you need to take not of is EOL errors on ESLint. Ensure you add an extra line at the end of your _.js_ files. I noticed you did not add an extra line to the _.babelrc_, _.env_, and _.eslintrc_ files.

Lastly, your _.env.example_ file is not complete. This is important so that devs that will work on this repo will have an idea of how to set up their dev environment.

Kindly effect these changes as soon as you can. Good job, man!

**Comment by Veraclins** [comment]
Thanks, @madeofhuman for your feedback. I have made the changes as suggested. Please review and let me know what you think.
Thanks.

**Review by madeofhuman — APPROVED** [review]
Good job, Clinton!

**Review by tonymontaro — APPROVED** [review]
Excellent collaboration, keep this up.

**Pull request merged**
