### PR TITLE
#159204727 User Tag Articles

### PR DESCRIPTION
**Pull request by yomigeek**
#### What does this PR do?
It enables users to tag a newly created article

#### Description of Task to be completed?
ensures user can add tags 
user can add more than one tag

#### How should this be manually tested?
- Clone the repo: Run git clone https://github.com/andela/elven-ah.git in the folder where you want the repo to be saved.
- Navigate into the newly created folder and install the dependencies: cd elven-ah && npm install
- Copy .env.example to .env: cp .env.example .env
- Provision a PostgreSQL database and add the credentials to the .env file.
- Start the server using npm start
- create an account and create an article or seed some articles
- Make a POST request to http://localhost:3000/api/articles using postman
- Create an article providing the title, categoryId, body, tags
- Write unit test(s)

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/159204727

### CODE REVIEW

**Review by Oluwafayokemi — COMMENTED** [review]
Nice work! Yomi!
One needful thing is to try to resolve all the hound issues.

**Review by Oluwafayokemi — APPROVED** [review]
Well done @yomigeek

**Review by Veraclins — APPROVED** [review]
Good job @yomigeek. You did a nice job and I will advise that you keep it up.

**Review by madeofhuman — APPROVED** [review]
You did a great job finishing this task, @yomigeek. Keep it up.

**Pull request merged**
